name: youcancode
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  # https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: ^2.6.1
  # https://pub.dev/packages/riverpod_annotation
  riverpod_annotation: ^2.6.1
  # https://pub.dev/packages/go_router
  go_router: ^14.3.0
  # https://pub.dev/packages/retrofit
  retrofit: ^4.4.1
  # https://pub.dev/packages/dio
  dio: ^5.7.0
  # https://pub.dev/packages/dio_http_formatter
  dio_http_formatter: ^3.2.1
  # https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^2.4.4
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0
  # https://pub.dev/packages/intl
  intl: ^0.19.0
  # https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^9.2.2
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.11


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  retrofit_generator: ^9.1.2
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  riverpod_generator: ^2.6.2
  flutter_gen_runner: ^5.8.0


flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/


